MESD\BgProcess\BgProcessBundle\Entity\BackgroundProcess:
    type: entity
    table: background_process
    repositoryClass: MESD\BgProcess\BgProcessBundle\Repository\BackgroundProcessRepository
    fields:
        id:
            column: id
            type: integer
            id: true
            generator:
                strategy: AUTO
        started:
            column: started
            type: datetime
            nullable: false
        updated:
            column: updated
            type: datetime
            nullable: true
        message:
            column: message
            type: text
            nullable: true
        toProcess:
            column: to_process
            type: integer
            nullable: false
        processed:
            column: processed
            type: integer
            nullable: false
        successCount:
            column: success_count
            type: integer
            nullable: false
        processParameters:
            column: process_parameters
            type: text
            nullable: true
        processId:
            column: process_id
            type: integer
            nullable: true

    manyToOne:
        processType:
            targetEntity: ProcessType
            joinColumn:
                name: process_type_id
        statusType:
            targetEntity: StatusType
            joinColumn:
                name: status_type_id

    lifecycleCallbacks:
        prePersist: [ setUpdatedValue ]
        preUpdate: [ setUpdatedValue ]