MESD\BgProcess\BgProcessBundle\Entity\BackgroundProcess:
    type: entity
    table: background_process
    repositoryClass: MESD\BgProcess\BgProcessBundle\Repository\BackgroundProcessRepository
    fields:
        id:
            column: id
            type: integer
            id: true
            generator:
                strategy: AUTO
        started:
            column: started
            type: datetime
            nullable: false
        updated:
            column: updated
            type: datetime
            nullable: true
        processType:
            column: processType
            type: string
            length: 32
            nullable: true
        status:
            column: status
            type: string
            length: 32
            nullable: false
        message:
            column: message
            type: text
        toProcess:
            column: to_process
            type: integer
        processed:
            column: processed
            type: integer
        successCount:
            column: success_count
            type: integer

    lifecycleCallbacks:
        prePersist: [ setUpdatedValue ]
        preUpdate: [ setUpdatedValue ]