<?php

namespace Mesd\BgProcessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BackgroundProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusTypeRepository extends EntityRepository
{
}
